
collections:
  banchi:
    output: true
    permalink: /:name
    order:
      - donnola-che-fa-la-doccia
      - gorilla-lisergico
      - materiali-vivi

defaults:
  - scope:
      path: ""
      type: "banchi"
    values:
      layout: banco
