
collections:
  banchi:
    output: true
    permalink: /:name
    order:
      - donnola-che-fa-la-doccia.md
      - gorilla-lisergico.md
      - materiali-vivi.md
      - annegamento.md

defaults:
  - scope:
      path: ""
      type: "banchi"
    values:
      layout: banco
